import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  input: {
    marginLeft: 16,
    width: '90%',
    height: 50,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 6,
    marginTop: 15,
    paddingLeft: 10,
    fontSize: 22,
    backgroundColor: 'white',
  },
  disabledInput: {
    marginLeft: 16,
    width: '90%',
    height: 50,
    borderWidth: 1,
    borderColor: '#D3D3D3',
    borderRadius: 6,
    marginTop: 15,
    fontSize: 22,
    paddingLeft: 10,
  },
  DatePicker: {
    top: 150,
    alignSelf: 'center',
    width: 350,
    height: 350,
    backgroundColor: 'white',
    elevation: 20,
    shadowColor: '#52006A',
    position: 'absolute',
  },
  absolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  imageContainer: {
    borderWidth: 0,
    borderRadius: 6,
    width: 150,
    height: 140,
    justifyContent: 'space-between',
  },
  iconContainer: {
    backgroundColor: 'gray',
    borderWidth: 0,
    borderRadius: 6,
    width: 150,
    height: 140,
    justifyContent: 'space-between',
  },
  icon: {
    marginTop: 8,
    fontSize: 120,
  },
  button: {
    backgroundColor: 'rgba(128, 0, 128, 0.8)',
    height: 50,
    width: 170,
    borderRadius: 6,
    marginTop: 20,
    paddingBottom: 10,
    paddingTop: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 22,
    textAlign: 'center',
  },
  buttonSave: {
    backgroundColor: 'rgba(46, 170, 62, 0.7)',
    height: 50,
    width: 120,
    borderRadius: 6,
    marginTop: 20,
    paddingBottom: 10,
    paddingTop: 10,
  },
  buttonCancel: {
    marginLeft: 35,
    backgroundColor: 'rgba(181, 0, 14, 0.7)',
    height: 50,
    width: 120,
    borderRadius: 6,
    marginTop: 20,
    paddingBottom: 10,
    paddingTop: 10,
  },
  viewButtons: {
    width: '100%',
    flex: 1,
    flexDirection: 'row',
    marginLeft: 45,
  },
  imagePickerView: {
    width: '100%',
    alignItems: 'center',
    marginTop: 50,
  },
  dateInput: {
    width: 80,
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    alignItems: 'center',
  },
  checkbox: {
    alignSelf: 'center',
  },
  datePickerInput: {
    marginLeft: 16,
    width: '90%',
    height: 50,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 6,
    marginTop: 15,
    paddingLeft: 10,
    fontSize: 22,
    backgroundColor: 'white',
    paddingBottom: 10,
    paddingTop: 10,
  },
  datePickerText: {
    color: '#949494',
    fontSize: 22,
  },
});
